[tool.poetry]
name = "image-to-midi"
version = "0.1.0"
description = ""
authors = ["tshippen <TShippen@barnard.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
